import React, { useEffect, useState } from 'react';
import { Download, FileAudio, FileJson, Link2, Radio, Repeat2, Square, Trash2, X } from 'lucide-react';
import { sampleInstrumentEngine } from '../audio/sampleInstrumentEngine';
import { SimulationEngine } from '../simulation/engine';
import { origoMusicSystem, PreparedMusicExport } from '../music/musicSystem';
import { InstrumentPanel } from './InstrumentPanel';
import { MusicalAnalysisPanel } from './MusicalAnalysisPanel';
import { PhraseModelPanel } from './PhraseModelPanel';
import { SampleRackPanel } from './SampleRackPanel';

type ExportKind = 'wav' | 'midi' | 'session' | 'aether';
interface ReadyDownload { url: string; filename: string; label: string; }

export function MusicCapturePanel({ engine }: { engine: SimulationEngine }) {
  const [, refresh] = useState(0); const [rendering, setRendering] = useState(false); const [feedingBack, setFeedingBack] = useState(false); const [showAdvanced, setShowAdvanced] = useState(false); const [readyDownload, setReadyDownload] = useState<ReadyDownload | null>(null); const [exportError, setExportError] = useState<string | null>(null);
  useEffect(() => { const rerender = () => refresh((v) => v + 1); const unsubMusic = origoMusicSystem.subscribe(rerender); const unsubSamples = sampleInstrumentEngine.subscribe(rerender); return () => { unsubMusic(); unsubSamples(); }; }, []);
  useEffect(() => () => { if (readyDownload?.url) URL.revokeObjectURL(readyDownload.url); }, [readyDownload]);
  const status = origoMusicSystem.getStatus(); const sampleStatus = sampleInstrumentEngine.getStatus(); const hasEvents = status.eventCount > 0;
  const publishArtifact = (artifact: PreparedMusicExport | null) => { if (!artifact) throw new Error('There is no captured material to export yet.'); const url = URL.createObjectURL(artifact.blob); setReadyDownload({ url, filename: artifact.filename, label: artifact.label }); };
  const prepareExport = async (kind: ExportKind) => { setExportError(null); if (kind === 'wav') setRendering(true); try { if (kind === 'wav') publishArtifact(await origoMusicSystem.prepareWav()); else if (kind === 'midi') publishArtifact(origoMusicSystem.prepareMidi()); else if (kind === 'session') publishArtifact(origoMusicSystem.prepareSessionJson()); else publishArtifact(origoMusicSystem.prepareAetherManifest()); } catch (error) { setExportError(error instanceof Error ? error.message : 'Unable to prepare the download.'); } finally { if (kind === 'wav') setRendering(false); } };
  const feedBack = async () => { setFeedingBack(true); try { await origoMusicSystem.feedTakeBackAsLoop(true); } finally { setFeedingBack(false); } };

  return <div className="space-y-3"><section className="border border-[#262626] bg-[#080808] p-3 font-mono">
    <div className="flex items-start justify-between gap-3"><div><p className="text-[9px] uppercase tracking-[0.2em] text-[#777]">World Recorder</p><p className="mt-1 text-xs font-sans font-medium text-white">Capture this ecosystem as a real track</p><p className="mt-1 text-[10px] font-sans leading-relaxed text-[#777]">Origo remembers musical events, ecological sections and recurring motifs while this world is alive. Exported files are artifacts; they are not a save-game/resume system.</p></div><div className={`flex items-center gap-1.5 border px-2 py-1 text-[8px] uppercase tracking-widest ${status.recording ? 'border-[#ff3e00] text-[#ff3e00]' : 'border-[#333] text-[#666]'}`}><span className={`h-1.5 w-1.5 rounded-full ${status.recording ? 'bg-[#ff3e00] animate-pulse' : 'bg-[#444]'}`} />{status.recording ? 'Recording' : hasEvents ? 'Captured' : 'Ready'}</div></div>
    <div className="mt-3 grid grid-cols-5 gap-2 text-center"><RecorderStat value={status.eventCount} label="Events" accent="text-[#00ff41]" /><RecorderStat value={status.barsCaptured} label="Bars" accent="text-white" /><RecorderStat value={status.motifCount} label="Motifs" accent="text-[#b283ff]" /><RecorderStat value={status.sectionCount ?? 0} label="Sections" accent="text-[#ffb24a]" /><RecorderStat value={engine.activePreset.soundPreset.tempoBpm} label="BPM" accent="text-[#ff6538]" /></div>
    {status.currentSection && <div className="mt-2 border border-[#ffb24a]/25 bg-[#171006] px-2.5 py-2 text-[9px] uppercase tracking-wider text-[#ffb24a]">Ecology: {status.currentSection}</div>}
    {sampleStatus.aetherLoop.armed && !status.recording && <div className="mt-2 border border-[#00ff41]/30 bg-[#061209] px-2.5 py-2 text-[9px] uppercase tracking-wider text-[#70ff91]">Return layer armed · Record New Take launches both at bar zero</div>}
    <div className="mt-3 flex gap-2">{!status.recording ? <button onClick={() => origoMusicSystem.start(engine)} className="flex flex-1 items-center justify-center gap-1.5 border border-[#00ff41] bg-[#00ff41] px-3 py-2.5 text-[9px] font-bold uppercase tracking-wider text-black transition hover:bg-[#62ff86]"><Radio className="h-3.5 w-3.5" /> {hasEvents ? 'Record New Take' : 'Start Recording'}</button> : <button onClick={() => origoMusicSystem.stop()} className="flex flex-1 items-center justify-center gap-1.5 border border-[#ff3e00] bg-[#ff3e00]/10 px-3 py-2.5 text-[9px] font-bold uppercase tracking-wider text-[#ff3e00] transition hover:bg-[#ff3e00] hover:text-black"><Square className="h-3.5 w-3.5" /> Stop & Keep Take</button>}<button onClick={() => origoMusicSystem.clear()} disabled={!hasEvents && !status.recording} className="border border-[#333] px-3 py-2 text-[#777] transition hover:text-white disabled:opacity-30" title="Clear this living capture"><Trash2 className="h-3.5 w-3.5" /></button></div>
    {hasEvents && !status.recording && <div className="mt-3 border-t border-[#222] pt-3"><p className="mb-2 text-[8px] uppercase tracking-[0.18em] text-[#666]">Build from this take</p><button disabled={feedingBack} onClick={feedBack} className="mb-2 flex w-full items-center justify-center gap-1.5 border border-[#ffb24a]/70 bg-[#ffb24a]/5 px-3 py-2.5 text-[9px] font-bold uppercase tracking-wider text-[#ffb24a] transition hover:bg-[#ffb24a] hover:text-black disabled:opacity-40"><Repeat2 className="h-3.5 w-3.5" /> {feedingBack ? 'Rendering Return Layer…' : sampleStatus.aetherLoop.armed ? 'Return Layer Armed for Next Take' : 'Feed Take Back In · Arm Next Layer'}</button><p className="mb-3 text-[9px] font-sans leading-relaxed text-[#666]">Renders this take into the Aether Return Loop and arms it. When you press Record New Take, the loop and the new recording begin together at that take's bar zero.</p><p className="mb-2 text-[8px] uppercase tracking-[0.18em] text-[#666]">Export artifact</p><div className="grid grid-cols-3 gap-2"><ExportButton disabled={rendering} onClick={() => void prepareExport('wav')} icon={<FileAudio className="h-3 w-3" />} label={rendering ? 'Rendering' : 'WAV'} primary /><ExportButton onClick={() => void prepareExport('midi')} icon={<Download className="h-3 w-3" />} label="MIDI" /><ExportButton onClick={() => void prepareExport('session')} icon={<FileJson className="h-3 w-3" />} label="Data" /></div>{readyDownload && <div className="mt-2 border border-[#00ff41]/30 bg-[#061209] p-2.5"><div className="flex items-center justify-between gap-2"><div className="min-w-0"><p className="text-[8px] uppercase tracking-widest text-[#70ff91]">{readyDownload.label} ready</p><p className="mt-0.5 truncate text-[8px] font-sans text-[#666]">{readyDownload.filename}</p></div><button onClick={() => setReadyDownload(null)} className="p-1 text-[#555] hover:text-white" aria-label="Dismiss prepared download"><X className="h-3 w-3" /></button></div><a href={readyDownload.url} download={readyDownload.filename} className="mt-2 flex w-full items-center justify-center gap-1.5 border border-[#00ff41] bg-[#00ff41] px-3 py-2.5 text-[9px] font-bold uppercase tracking-wider text-black hover:bg-[#70ff91]"><Download className="h-3.5 w-3.5" /> Save {readyDownload.label}</a><p className="mt-1.5 text-[8px] font-sans leading-relaxed text-[#555]">This explicit save link stays on screen so browsers cannot silently swallow an asynchronous export.</p></div>}{exportError && <p className="mt-2 border border-[#ff3e00]/30 bg-[#1a0905] p-2 text-[9px] font-sans leading-relaxed text-[#ff7653]">{exportError}</p>}</div>}
    <button onClick={() => setShowAdvanced((value) => !value)} className="mt-3 flex w-full items-center justify-between border-t border-[#202020] pt-2 text-left text-[8px] uppercase tracking-[0.16em] text-[#555] hover:text-[#999]"><span>Libertas / AetherStream</span><span>{showAdvanced ? '−' : '+'}</span></button>
    {showAdvanced && <div className="mt-2 border border-[#202020] bg-[#0b0b0b] p-2.5"><p className="font-sans text-[10px] leading-relaxed text-[#777]">Libertas Desktop remains the authoritative musical clock. Origo can send deterministic session/section data outward, while rendered stems or loops can return through the Sample Rack for another generative pass.</p><button disabled={!hasEvents} onClick={() => void prepareExport('aether')} className="mt-2 flex w-full items-center justify-center gap-1.5 border border-[#333] px-2 py-2 text-[8px] uppercase tracking-wider text-[#aaa] hover:border-[#ff3e00] hover:text-[#ff6538] disabled:opacity-30"><Link2 className="h-3 w-3" /> Prepare Aether Manifest</button></div>}
  </section><MusicalAnalysisPanel /><PhraseModelPanel /><SampleRackPanel /><InstrumentPanel /></div>;
}
function RecorderStat({ value, label, accent }: { value: number; label: string; accent: string }) { return <div className="border border-[#1f1f1f] bg-[#0b0b0b] p-2"><div className={`text-sm ${accent}`}>{value}</div><div className="text-[7px] uppercase tracking-widest text-[#555]">{label}</div></div>; }
function ExportButton({ onClick, icon, label, disabled = false, primary = false }: { onClick: () => void; icon: React.ReactNode; label: string; disabled?: boolean; primary?: boolean }) { return <button disabled={disabled} onClick={onClick} className={`flex items-center justify-center gap-1 border px-2 py-2 text-[8px] uppercase tracking-wider transition disabled:opacity-30 ${primary ? 'border-[#00ff41]/60 text-[#00ff41] hover:bg-[#00ff41] hover:text-black' : 'border-[#333] text-[#aaa] hover:border-[#00ff41] hover:text-[#00ff41]'}`}>{icon}{label}</button>; }
